name: Wurfelt
main: me.misoryan.wurfelt.Wurfelt
version: 1.1-1905010-hank9999fix
author: Misoryan
description: Best Basic Plugin for 1.8+ Server!
api-version: 1.13

softdepend: [ActionBarAPI]

permissions:
  Wurfelt.admin:
    default: op
    children:
      Wurfelt.SS: true
  Wurfelt.SS:
    description: Permission to use Freeze (Screen Share) Command.
    default: op

commands:
  wurfelt:
    description: Main Command.
  freeze:
    description: Freeze a player to use SS.
  report:
    aliases: [wdr]
  reports: